import xiaomiRedmi from './assets/xiaomiRedmi.jpg';
import xiaomiPoco from './assets/xiaomiPoco.jpg';
import vivo from './assets/vivo.jpg';
import samsungS21 from './assets/samsungS21.jpg';
import samsungS22 from './assets/samsungS22.jpg';
import samsungA12 from './assets/samsungA12.jpg';
import samsungFold from './assets/samsungFold.jpg';
import iphone11 from './assets/iphone11.jpg';
import iphone11Red from './assets/iphone11Red.jpg';
import iphoneX from './assets/iphoneX.jpg';
import iphoneXs from './assets/iphoneXs.jpg';
import iphoneXsMax from './assets/iphoneXsMax.jpg';
import iphone13Pro from './assets/iphone13Pro.jpg';
import iphone13ProMax from './assets/iphone13ProMax.jpg';
import iphone11ProMax from './assets/iphone11ProMax.jpg';
import iphone8 from './assets/iphone8.jpg';
import galaxyM31 from './assets/galaxyM31.jpg';
import xiaomiMi4 from './assets/xiaomiMi4.jpg';
import xiaomi11T from './assets/xiaomi11T.jpg';
import xiaomiMi11i from './assets/xiaomiMi11i.jpg';
import iPhoneSE from './assets/iPhoneSE.jpg';
import iPhoneSeRed from './assets/iPhoneSeRed.jpg';
import galaxyS21Ultra from './assets/galaxyS21Ultra.jpg';

export interface IProduct {
  "id": string,
  "name": string,
  "src": string | null,
  "alt": string,
  "amount": number | string,
  "year": number | string,
  "price": number | string,
  "mark": string,
  "color": string,
  "amountOfCamera": number | string,
  "isPopular": boolean,
}

export interface IFiltersList {[key: string]: string | string[] | boolean}

export const listFiltersDefault: IFiltersList = {
  'mark': [],
  'amountOfCamera': [],
  'color': [],
  'isPopular': false,
  'amount': ['1', '40'],
  'year': ['2010', '2022'],
  'name': '',
  'sorting': 'textUp',
}

export const catalog:IProduct[] = [
  {
    "id": 'pr01',
    "name": "Iphone 11",
    "src": iphone11,
    "alt": "Iphone 11",
    "amount": 23,
    "year": 2020,
    "price": 800,
    "mark": "Apple",
    "color": "white",
    "amountOfCamera": 2,
    "isPopular": true,
  },
  {
    "id": 'pr02',
    "name": "Samsung Z Fold",
    "src": samsungFold,
    "alt": "Samsung Z Fold",
    "amount": 11,
    "year": 2022,
    "price": 1800,
    "mark": "Samsung",
    "color": "black",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr03',
    "name": "Iphone 11",
    "src": iphone11Red,
    "alt": "Iphone 11",
    "amount": 23,
    "year": 2020,
    "price": 800,
    "mark": "Apple",
    "color": "red",
    "amountOfCamera": 2,
    "isPopular": false,
  },
  {
    "id": 'pr04',
    "name": "Samsung A 12",
    "src": samsungA12,
    "alt": "Samsung A 12",
    "amount": 30,
    "year": 2021,
    "price": 600,
    "mark": "Samsung",
    "color": "white",
    "amountOfCamera": 4,
    "isPopular": true,
  },
  {
    "id": 'pr05',
    "name": "Iphone 8 Plus",
    "src": iphone8,
    "alt": "Iphone 8 Plus",
    "amount": 2,
    "year": 2018,
    "price": 700,
    "mark": "Apple",
    "color": "white",
    "amountOfCamera": 2,
    "isPopular": true,
  },
  {
    "id": 'pr06',
    "name": "Xiaomi Redmi 10",
    "src": xiaomiRedmi,
    "alt": "Xiaomi Redmi 10",
    "amount": 25,
    "year": 2021,
    "price": 700,
    "mark": "Xiaomi",
    "color": "black",
    "amountOfCamera": 4,
    "isPopular": false,
  },
  {
    "id": 'pr07',
    "name": "Samsung Galaxy S 21",
    "src": samsungS21,
    "alt": "Samsung Galaxy S 21",
    "amount": 30,
    "year": 2021,
    "price": 900,
    "mark": "Samsung",
    "color": "white",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr08',
    "name": "Iphone 11 Pro Max",
    "src": iphone11ProMax,
    "alt": "Iphone 11Pro Max",
    "amount": 23,
    "year": 2020,
    "price": 950,
    "mark": "Apple",
    "color": "green",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr09',
    "name": "Iphone X",
    "src": iphoneX,
    "alt": "Iphone X",
    "amount": 12,
    "year": 2018,
    "price": 600,
    "mark": "Apple",
    "color": "white",
    "amountOfCamera": 2,
    "isPopular": true,
  },
  {
    "id": 'pr10',
    "name": "Xiaomi Poco F3",
    "src": xiaomiPoco,
    "alt": "Xiaomi Poco F3",
    "amount": 25,
    "year": 2021,
    "price": 500,
    "mark": "Xiaomi",
    "color": "white",
    "amountOfCamera": 3,
    "isPopular": false,
  },
  {
    "id": 'pr11',
    "name": "Iphone Xs",
    "src": iphoneXs,
    "alt": "Iphone Xs",
    "amount": 12,
    "year": 2019,
    "price": 650,
    "mark": "Apple",
    "color": "black",
    "amountOfCamera": 2,
    "isPopular": false,
  },
  {
    "id": 'pr12',
    "name": "Samsung Galaxy S 22 Ultra",
    "src": samsungS22,
    "alt": "Samsung Galaxy S 22 Ultra",
    "amount": 30,
    "year": 2022,
    "price": 1100,
    "mark": "Samsung",
    "color": "white",
    "amountOfCamera": 4,
    "isPopular": false,
  },
  {
    "id": 'pr13',
    "name": "Iphone Xs Max",
    "src": iphoneXsMax,
    "alt": "Iphone Xs Max",
    "amount": 15,
    "year": 2019,
    "price": 750,
    "mark": "Apple",
    "color": "white",
    "amountOfCamera": 2,
    "isPopular": true,
  },
  {
    "id": 'pr14',
    "name": "Iphone 13 Pro Max",
    "src": iphone13ProMax,
    "alt": "Iphone 13Pro Max",
    "amount": 25,
    "year": 2022,
    "price": 1150,
    "mark": "Apple",
    "color": "white",
    "amountOfCamera": 3,
    "isPopular": false,
  },
  {
    "id": 'pr15',
    "name": "Vivo Y20",
    "src": vivo,
    "alt": "Vivo Y20",
    "amount": 9,
    "year": 2021,
    "price": 450,
    "mark": "Vivo",
    "color": "blue",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr16',
    "name": "Iphone 13 Pro",
    "src": iphone13Pro,
    "alt": "Iphone 13Pro",
    "amount": 20,
    "year": 2022,
    "price": 1050,
    "mark": "Apple",
    "color": "blue",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr17',
    "name": "Samsung Galaxy M31",
    "src": galaxyM31,
    "alt": "Samsung Galaxy M31",
    "amount": 17,
    "year": 2020,
    "price": 300,
    "mark": "Samsung",
    "color": "blue",
    "amountOfCamera": 4,
    "isPopular": false,
  },
  {
    "id": 'pr18',
    "name": "Xiaomi Mi4 3",
    "src": xiaomiMi4,
    "alt": "Xiaomi Mi4 3",
    "amount": 8,
    "year": 2014,
    "price": 350,
    "mark": "Xiaomi",
    "color": "white",
    "amountOfCamera": 2,
    "isPopular": false,
  },
  {
    "id": 'pr19',
    "name": "Xiaomi 11T",
    "src": xiaomi11T,
    "alt": "Xiaomi 11T",
    "amount": 14,
    "year": 2021,
    "price": 500,
    "mark": "Xiaomi",
    "color": "white",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr20',
    "name": "Xiaomi Mi 11i",
    "src": xiaomiMi11i,
    "alt": "Xiaomi Mi 11i",
    "amount": 27,
    "year": 2021,
    "price": 700,
    "mark": "Xiaomi",
    "color": "black",
    "amountOfCamera": 3,
    "isPopular": true,
  },
  {
    "id": 'pr21',
    "name": "Iphone SE",
    "src": iPhoneSE,
    "alt": "iPhone SE",
    "amount": 11,
    "year": 2016,
    "price": 380,
    "mark": "Apple",
    "color": "black",
    "amountOfCamera": 1,
    "isPopular": false,
  },
  {
    "id": 'pr22',
    "name": "Iphone SE",
    "src": iPhoneSeRed,
    "alt": "iPhone SE",
    "amount": 31,
    "year": 2016,
    "price": 420,
    "mark": "Apple",
    "color": "red",
    "amountOfCamera": 1,
    "isPopular": false,
  },
  {
    "id": 'pr23',
    "name": "Samsung Galaxy S21 Ultra",
    "src": galaxyS21Ultra,
    "alt": "Samsung Galaxy S21 Ultra",
    "amount": 23,
    "year": 2021,
    "price": 860,
    "mark": "Samsung",
    "color": "black",
    "amountOfCamera": 4,
    "isPopular": true,
  },
]
